name: Unified Multi-Account Workflow (v3.7 IssueFix)

on:
  workflow_dispatch:
    inputs:
      total_commits:
        description: "Jumlah total commit per akun"
        required: true
        default: "1650"
      total_days:
        description: "Jumlah hari pembagian commit"
        required: true
        default: "365"
      total_prs:
        description: "Jumlah Pull Request per akun"
        required: true
        default: "120"
      total_issues:
        description: "Jumlah Issue per akun"
        required: true
        default: "130"
      repo_count:
        description: "Jumlah repository tambahan per akun"
        required: true
        default: "25"
      target_repo:
        description: "Repository utama tempat aktivitas"
        required: true
        default: "anjaymabarselebew/hapuss"

jobs:
  unified:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 9
      matrix:
        include:
          - account: HuangWendell
            email: 10686160+HuangWendell@users.noreply.github.com
            token_secret: PAT1
          - account: wellscho
            email: 17506678+wellscho@users.noreply.github.com
            token_secret: PAT2
          - account: wellington1367
            email: 26806849+wellington1367@users.noreply.github.com
            token_secret: PAT3
          - account: naxhonrox
            email: 38462880+naxhonrox@users.noreply.github.com
            token_secret: PAT4
          - account: christiandelanhol
            email: 85139679+christiandelanhol@users.noreply.github.com
            token_secret: PAT5
          - account: Magateu
            email: 83436528+Magateu@users.noreply.github.com 
            token_secret: PAT6
          - account: willwang623
            email: 91578547+willwang623@users.noreply.github.com 
            token_secret: PAT7
          - account: arthurcostaPiovezan
            email: 129125297+arthurcostaPiovezan@users.noreply.github.com
            token_secret: PAT8
          - account: JSBryanAriasH
            email: 122652964+JSBryanAriasH@users.noreply.github.com
            token_secret: PAT9
          - account: lingxiaoduan
            email: 127101506+lingxiaoduan@users.noreply.github.com
            token_secret: PAT10
          
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Delay Awal
        run: |
          DELAY=$((5 + RANDOM % 10))
          echo "🕒 Delay awal $DELAY detik untuk akun ${{ matrix.account }}..."
          sleep $DELAY

      - name: Setup Git
        run: |
          git config --global user.name "${{ matrix.account }}"
          git config --global user.email "${{ matrix.email }}"
          echo "✅ Git identity diset untuk ${{ matrix.account }}"

      - name: Clone Target Repo
        env:
          GH_TOKEN: ${{ secrets[matrix.token_secret] }}
          TARGET_REPO: ${{ github.event.inputs.target_repo }}
        run: |
          git clone --filter=blob:none --depth=1 https://x-access-token:${GH_TOKEN}@github.com/$TARGET_REPO repo
          cd repo
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${TARGET_REPO}.git

      - name: Commit Generator (fast author tracking)
        env:
          TOTAL_COMMITS: ${{ github.event.inputs.total_commits }}
          TOTAL_DAYS: ${{ github.event.inputs.total_days }}
          GH_TOKEN: ${{ secrets[matrix.token_secret] }}
          TARGET_REPO: ${{ github.event.inputs.target_repo }}
        run: |
          cd repo
          mkdir -p logs
          COMMITS_PER_DAY=$((TOTAL_COMMITS / TOTAL_DAYS))
          START_DATE=$(date -d "$TOTAL_DAYS days ago" +%Y-%m-%d)
          for ((day=0; day<TOTAL_DAYS; day++)); do
            DATE_STR=$(date -d "$START_DATE +$day days" +%Y-%m-%d)
            FILE="logs/${{ matrix.account }}_$day.txt"
            for ((i=1; i<=COMMITS_PER_DAY; i++)); do
              echo "Commit $i oleh ${{ matrix.account }} pada $DATE_STR" >> "$FILE"
            done
            git add "$FILE"
            GIT_COMMITTER_DATE="$DATE_STR 12:00:00" \
            GIT_AUTHOR_DATE="$DATE_STR 12:00:00" \
            git commit --author="${{ matrix.account }} <${{ matrix.email }}>" -m "Auto commits by ${{ matrix.account }} on $DATE_STR" || true
          done

          DELAY_PUSH=$((5 + RANDOM % 15))
          echo "⏳ Delay $DELAY_PUSH detik sebelum push (anti tabrakan)"
          sleep $DELAY_PUSH

          ATTEMPT=1
          until [ $ATTEMPT -gt 3 ]; do
            git fetch origin main || true
            git pull --rebase --autostash origin main || true
            if git push https://x-access-token:${GH_TOKEN}@github.com/$TARGET_REPO HEAD:main; then
              echo "✅ Push sukses (attempt $ATTEMPT)"
              break
            fi
            echo "⚠️ Retry push ($ATTEMPT)..."
            sleep $((2 * ATTEMPT))
            ATTEMPT=$((ATTEMPT+1))
          done
